checksume = "1186389a11e470f4a584b2325704c68142da6a09369b9a661bed0f2ed87bdd68"
licence = "GPL-3.0-or-later AND LGPL-2.1-only"
meta = false
provides = "calamares-mod-netinstall"
service_directory = ""
tarball = "http://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64"
version = "3.2.45-r0"

[commands]
  compile = "echo"
  configure = "echo"
  install = "{{ .ManifestDir }}/install.sh"
  patches = []
  skipenv = false
  working_dir = "."

[profiles]

  [profiles.default]
    Deps = [["ckbcomp", "1.205-r0"], ["musl-locales", "0_git20201005-r0"], ["os-prober", "1.79-r0"], ["kcoreaddons", "5.88.0-r0"], ["qt5-qtbase", "5.15.3_git20210713-r5"], ["qt5-qtbase-x11", "5.15.3_git20210713-r5"], ["musl", "1.2.2-r7"], ["calamares", "3.2.45-r0"], ["libgcc", "10.3.1_git20211027-r0"], ["libstdc++", "10.3.1_git20211027-r0"], ["yaml-cpp", "0.6.3-r1"]]
